### PR TITLE
remove lawnchair and add my maintainer name pls

### PR DESCRIPTION
**Pull request by justanuserxd**

### CODE REVIEW

**Comment by Lambada10** [comment]
LMFAO

**Comment by xAbdaziz** [comment]
Lmao

**Comment by clhexftw** [comment]
salute to this legend

**Comment by justks** [comment]
Sahil, you tried but this is not how you contribute - I will just assume this is something you did not intend to PR and close it.
https://opensource.guide/how-to-contribute/

**Pull request closed without merging**
